### ISSUE TITLE
Language summary totals includes PRs

### ISSUE THREAD

**Issue by danoscarmike** [JustinBeckwith/sloth#13]
## Observed behavior:
(at 13:48PT, 2018-07-18)

`sloth --api pubsub --csv` returns:
```
Language,Total,P0,P1,P2,Untriaged,Out of SLO
go,4,0,2,2,0,1
nodejs,20,0,3,10,2,8
ruby,1,0,0,1,0,0
python,6,0,0,4,0,1
php,3,0,0,0,0,0
dotnet,0,0,0,0,0,0
java,16,0,4,11,0,8
```
Interrogating PHP with the GitHub UI:
https://github.com/GoogleCloudPlatform/google-cloud-php/issues?q=is%3Aopen+is%3Aissue+label%3A%22api%3A+pubsub%22 lists only 2 issues

https://github.com/GoogleCloudPlatform/google-cloud-php/labels/api%3A%20pubsub lists three "objects" -- 1 PR and the 2 issues from before.

## Expected behavior
`sloth --api pubsub --csv` returns:
```
Language,Total,P0,P1,P2,Untriaged,Out of SLO
...
php,2,0,0,0,0,0
...
```

**Comment by JustinBeckwith** [comment]
Fixed in the latest version :)
