### ISSUE TITLE
FR: Identify triage and SLO status by adding/removing a label

### ISSUE THREAD

**Issue by danoscarmike** [JustinBeckwith/sloth#2]

**Comment by JustinBeckwith** [comment]
in 1.3 you can now run `sloth tag-issues` - enjoy ;)

**Comment by danoscarmike** [comment]
Mom, look! I had a feature request implemented! 

Giddy-up :)

**Comment by quartzmo** [comment]
And it's a good one. Already making it much easier to see where things are at.
