### ISSUE TITLE
Usability: Change Triaged to Untriaged in issues report

### ISSUE THREAD

**Issue by quartzmo** [JustinBeckwith/sloth#4]
Reverse the "Triaged" column to "Untriaged" to match the regular `sloth` report.

The two boolean columns in `sloth issues` are a bit hard to grok since in "Triaged" a true is a good thing and in "OOSLO" it's a bad thing. It'll be easier to scan the report if a `true` is always a flag for "needs attention".

#### sloth issues
<img width="948" alt="screen shot 2018-06-07 at 5 52 00 pm" src="https://user-images.githubusercontent.com/205445/41131983-93d090a4-6a7b-11e8-84d9-8b8dc94a12e0.png">

#### sloth
<img width="378" alt="screen shot 2018-06-07 at 5 52 17 pm" src="https://user-images.githubusercontent.com/205445/41131982-93bdabb0-6a7b-11e8-9b4c-ceb6e6300653.png">

**Comment by JustinBeckwith** [comment]
How's this? 

![image](https://user-images.githubusercontent.com/534619/41132848-4a2dc492-6a78-11e8-91aa-db60750ccc39.png)

🤣

**Comment by JustinBeckwith** [comment]
This is available in `sloth@1.2.2` which should on npm in a sec :)

**Comment by quartzmo** [comment]
Can the same symbol be used to represent the positive and negative states in "Triaged" and "In SLO"?

The implementation [assigns the same symbols](https://github.com/JustinBeckwith/sloth/blob/v1.3.0/src/issue.ts#L136-L137) to `isTriaged` as it does to `isOutOfSLO`, but `isTriaged` is the same as "Triaged", while `isOutOfSLO` is the opposite of "In SLO".

**Comment by JustinBeckwith** [comment]
That is a bug.  Missing a ! :) PR me?

**Comment by quartzmo** [comment]
👍  I'll do a PR now.
